import { describe, it, expect, vi, beforeEach } from "vitest";
import { parseCommand, generateDescription } from "../describe.js";

vi.mock("ai", () => ({
  generateObject: vi.fn(),
}));

vi.mock("../models.js", () => ({
  createModel: vi.fn(() => "mock-model"),
}));

vi.mock("../sanitize.js", () => ({
  sanitizeInput: vi.fn((s: string) => s),
}));

vi.mock("../diagram.js", () => ({
  generateArchDiagram: vi.fn(() => null),
}));

import { generateObject } from "ai";
const mockGenerateObject = vi.mocked(generateObject);

describe("parseCommand", () => {
  it("parses /mizumi describe", () => {
    const result = parseCommand("/mizumi describe");
    expect(result).toEqual({ command: "describe", args: "" });
  });

  it("parses /mizumi review with instructions", () => {
    const result = parseCommand("/mizumi review focus on security");
    expect(result).toEqual({ command: "review", args: "focus on security" });
  });

  it("returns null for non-mizumi commands", () => {
    expect(parseCommand("/other command")).toBeNull();
  });

  it("returns null for plain text", () => {
    expect(parseCommand("just a comment")).toBeNull();
  });

  it("parses /mizumi improve", () => {
    const result = parseCommand("/mizumi improve");
    expect(result?.command).toBe("improve");
  });

  it("parses /mizumi spend", () => {
    const result = parseCommand("/mizumi spend");
    expect(result?.command).toBe("spend");
  });

  it("parses /mizumi test", () => {
    const result = parseCommand("/mizumi test");
    expect(result?.command).toBe("test");
  });

  it("parses /mizumi trigger", () => {
    const result = parseCommand("/mizumi trigger");
    expect(result?.command).toBe("trigger");
  });

  it("handles extra whitespace in args", () => {
    const result = parseCommand("/mizumi review focus on security");
    expect(result?.command).toBe("review");
    expect(result?.args).toBe("focus on security");
  });

  it("returns null for /mizumi with no subcommand", () => {
    expect(parseCommand("/mizumi")).toBeNull();
  });

  it("parses /mizumi with numeric args", () => {
    const result = parseCommand("/mizumi review #42");
    expect(result?.args).toBe("#42");
  });
});

describe("generateDescription", () => {
  beforeEach(() => {
    mockGenerateObject.mockReset();
  });

  function makeConfig() {
    return {
      provider: "openai" as const, model: "gpt-4.1-mini", baseUrl: "",
      profile: "chill" as const, maxComments: 15, language: "en-US",
      selfCritique: true, confidenceThreshold: 80, autoReview: true,
      autoPauseAfter: 5, excludePatterns: [], tierRouting: true,
      smallDiffThreshold: 50, securityPaths: [],
    };
  }

  it("generates PR description from diff", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Add OAuth2 login",
        summary: "Implements OAuth2 authentication flow",
        changes: ["Add OAuth2 client", "Update auth middleware"],
        testing: "Run integration tests",
        breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff content", "Auth", "Fix login", makeConfig());
    expect(result).toContain("Add OAuth2 login");
    expect(result).toContain("OAuth2 authentication flow");
    expect(result).toContain("Add OAuth2 client");
    expect(result).toContain("Run integration tests");
    expect(result).toContain("Generated by Mizumi");
  });

  it("includes breaking changes section when present", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Update API",
        summary: "Breaking API change",
        changes: ["Remove /v1/endpoint"],
        testing: "Check migration guide",
        breaking: "Token format changed — existing tokens will be invalid",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", "Update", "API change", makeConfig());
    expect(result).toContain("Breaking Changes");
    expect(result).toContain("Token format changed");
  });

  it("omits breaking changes section when 'None'", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix bug",
        summary: "Fix null pointer",
        changes: ["Add null check"],
        testing: "Run tests",
        breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", "Fix", "bug", makeConfig());
    expect(result).not.toContain("Breaking Changes");
  });

  it("sanitizes input before sending to LLM", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix",
        summary: "Fix",
        changes: ["Fix"],
        testing: "Run",
        breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    await generateDescription("diff", "title", "body", makeConfig());

    const callOpts = mockGenerateObject.mock.calls[0][0] as any;
    expect(callOpts.prompt).toContain("title");
    expect(callOpts.prompt).toContain("body");
  });

  it("truncates diff to 50000 chars", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix",
        summary: "Fix",
        changes: ["Fix"],
        testing: "Run",
        breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const longDiff = "x".repeat(60000);
    await generateDescription(longDiff, "title", "body", makeConfig());

    const callOpts = mockGenerateObject.mock.calls[0][0] as any;
    const diffPart = callOpts.prompt.split("Diff:")[1];
    expect(diffPart.length).toBeLessThan(55000);
  });
});
