import { describe, it, expect, vi, beforeEach } from "vitest";
import { parseCommand, generateDescription } from "../describe.js";

vi.mock("ai", () => ({
  generateObject: vi.fn(),
}));

vi.mock("../models.js", () => ({
  createModel: vi.fn(() => "mock-model"),
}));

vi.mock("../sanitize.js", () => ({
  sanitizeInput: vi.fn((s: string) => s),
}));

vi.mock("../diagram.js", () => ({
  generateArchDiagram: vi.fn(() => null),
}));

import { generateObject } from "ai";
const mockGenerateObject = vi.mocked(generateObject);

describe("parseCommand", () => {
  it("parses /mizumi describe", () => {
    const result = parseCommand("/mizumi describe");
    expect(result).toEqual({ command: "describe", args: "" });
  });

  it("parses /mizumi review with instructions", () => {
    const result = parseCommand("/mizumi review focus on security");
    expect(result).toEqual({ command: "review", args: "focus on security" });
  });

  it("returns null for non-mizumi commands", () => {
    expect(parseCommand("/other command")).toBeNull();
  });

  it("returns null for plain text", () => {
    expect(parseCommand("just a comment")).toBeNull();
  });

  it("parses /mizumi improve", () => {
    const result = parseCommand("/mizumi improve");
    expect(result?.command).toBe("improve");
  });

  it("parses /mizumi spend", () => {
    const result = parseCommand("/mizumi spend");
    expect(result?.command).toBe("spend");
  });

  it("parses /mizumi test", () => {
    const result = parseCommand("/mizumi test");
    expect(result?.command).toBe("test");
  });

  it("parses /mizumi trigger", () => {
    const result = parseCommand("/mizumi trigger");
    expect(result?.command).toBe("trigger");
  });

  it("handles extra whitespace in args", () => {
    const result = parseCommand("/mizumi review focus on security");
    expect(result?.command).toBe("review");
    expect(result?.args).toBe("focus on security");
  });

  it("returns null for /mizumi with no subcommand", () => {
    expect(parseCommand("/mizumi")).toBeNull();
  });

  it("parses /mizumi with numeric args", () => {
    const result = parseCommand("/mizumi review #42");
    expect(result?.args).toBe("#42");
  });

  // --- New tests ---

  it("returns null for empty string", () => {
    expect(parseCommand("")).toBeNull();
  });

  it("parses /mizumi calibrate", () => {
    const result = parseCommand("/mizumi calibrate");
    expect(result?.command).toBe("calibrate");
  });

  it("parses /mizumi labels", () => {
    const result = parseCommand("/mizumi labels");
    expect(result?.command).toBe("labels");
  });

  it("parses /mizumi with multi-word args", () => {
    const result = parseCommand("/mizumi review check for SQL injection in auth");
    expect(result?.command).toBe("review");
    expect(result?.args).toBe("check for SQL injection in auth");
  });

  it("does not match /mizumi-style prefix (must be exact)", () => {
    expect(parseCommand("/mizumiextra command")).toBeNull();
  });

  it("returns null for command without leading slash", () => {
    expect(parseCommand("mizumi describe")).toBeNull();
  });
});

describe("generateDescription", () => {
  beforeEach(() => {
    mockGenerateObject.mockReset();
  });

  function makeConfig() {
    return {
      provider: "openai" as const, model: "gpt-4.1-mini", baseUrl: "",
      profile: "chill" as const, maxComments: 15, language: "en-US",
      selfCritique: true, confidenceThreshold: 80, autoReview: true,
      autoPauseAfter: 5, excludePatterns: [], tierRouting: true,
      smallDiffThreshold: 50, securityPaths: [],
    };
  }

  it("generates PR description from diff", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Add OAuth2 login",
        summary: "Implements OAuth2 authentication flow",
        changes: ["Add OAuth2 client", "Update auth middleware"],
        testing: "Run integration tests",
        breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff content", "Auth", "Fix login", makeConfig());
    expect(result).toContain("Add OAuth2 login");
    expect(result).toContain("OAuth2 authentication flow");
    expect(result).toContain("Add OAuth2 client");
    expect(result).toContain("Run integration tests");
    expect(result).toContain("Generated by Mizumi");
  });

  it("includes breaking changes section when present", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Update API",
        summary: "Breaking API change",
        changes: ["Remove /v1/endpoint"],
        testing: "Check migration guide",
        breaking: "Token format changed — existing tokens will be invalid",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", "Update", "API change", makeConfig());
    expect(result).toContain("Breaking Changes");
    expect(result).toContain("Token format changed");
  });

  it("omits breaking changes section when 'None'", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix bug",
        summary: "Fix null pointer",
        changes: ["Add null check"],
        testing: "Run tests",
        breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", "Fix", "bug", makeConfig());
    expect(result).not.toContain("Breaking Changes");
  });

  it("sanitizes input before sending to LLM", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix",
        summary: "Fix",
        changes: ["Fix"],
        testing: "Run",
        breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    await generateDescription("diff", "title", "body", makeConfig());

    const callOpts = mockGenerateObject.mock.calls[0][0] as any;
    expect(callOpts.prompt).toContain("title");
    expect(callOpts.prompt).toContain("body");
  });

  it("truncates diff to 50000 chars", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix",
        summary: "Fix",
        changes: ["Fix"],
        testing: "Run",
        breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const longDiff = "x".repeat(60000);
    await generateDescription(longDiff, "title", "body", makeConfig());

    const callOpts = mockGenerateObject.mock.calls[0][0] as any;
    const diffPart = callOpts.prompt.split("Diff:")[1];
    expect(diffPart.length).toBeLessThan(55000);
  });

  // --- New tests ---

  it("formats changes as bullet list", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Refactor auth",
        summary: "Refactored auth module",
        changes: ["Extract auth middleware", "Add unit tests", "Update docs"],
        testing: "npm test",
        breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", "Refactor", "auth", makeConfig());
    expect(result).toContain("- Extract auth middleware");
    expect(result).toContain("- Add unit tests");
    expect(result).toContain("- Update docs");
  });

  it("includes imperative mood title in heading", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Add logging module",
        summary: "Adds structured logging",
        changes: ["Add winston logger"],
        testing: "npm test",
        breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", "Title", "Body", makeConfig());
    expect(result).toContain("## Add logging module");
  });

  it("omits breaking changes section when undefined", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix",
        summary: "Fix typo",
        changes: ["Fix spelling"],
        testing: "Visual check",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", "Fix", "typo", makeConfig());
    expect(result).not.toContain("Breaking Changes");
  });

  it("includes system prompt for description generation", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix", summary: "Fix", changes: ["Fix"], testing: "Run", breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    await generateDescription("diff", "title", "body", makeConfig());
    const callOpts = mockGenerateObject.mock.calls[0][0] as any;
    expect(callOpts.system).toContain("structured PR descriptions");
    expect(callOpts.system).toContain("imperative mood");
  });

  it("passes maxOutputTokens 2048 to generateObject", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix", summary: "Fix", changes: ["Fix"], testing: "Run", breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    await generateDescription("diff", "title", "body", makeConfig());
    const callOpts = mockGenerateObject.mock.calls[0][0] as any;
    expect(callOpts.maxOutputTokens).toBe(2048);
  });

  it("passes diff files to generateArchDiagram when 2+ files provided", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Add feature", summary: "Adds new feature", changes: ["Add module A"],
        testing: "npm test", breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const diffFiles = [
      { path: "src/a.ts", additions: 10, deletions: 5 },
      { path: "src/b.ts", additions: 15, deletions: 3 },
    ];
    await generateDescription("diff", "Feature", "New feature", makeConfig(), diffFiles);
    // generateArchDiagram is mocked to return null, so no diagram in output
    const callOpts = mockGenerateObject.mock.calls[0][0] as any;
    expect(callOpts).toBeDefined();
  });

  it("skips arch diagram when fewer than 2 diff files", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix", summary: "Fix", changes: ["Fix typo"], testing: "Visual", breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const singleFile = [{ path: "src/a.ts", additions: 5, deletions: 2 }];
    const result = await generateDescription("diff", "Fix", "typo", makeConfig(), singleFile);
    expect(result).not.toContain("Change Architecture");
  });

  it("handles empty PR title gracefully", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Updates module", summary: "Various updates", changes: ["Refactor"],
        testing: "npm test", breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", "", "body text", makeConfig());
    expect(result).toContain("Updates module");
  });

  it("handles empty PR body gracefully", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Add feature", summary: "New feature", changes: ["Add X"],
        testing: "Run tests", breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", "Title", "", makeConfig());
    expect(result).toContain("Add feature");
  });

  it("includes Mizumi attribution in output", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix bug", summary: "Fixes crash", changes: ["Add null check"],
        testing: "npm test", breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", "Fix", "crash", makeConfig());
    expect(result).toContain("Generated by Mizumi");
  });

  it("formats output with proper markdown structure", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Refactor API", summary: "Refactors API layer",
        changes: ["Extract middleware", "Add validation"],
        testing: "Integration tests", breaking: "Token format changed",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", "Refactor", "API", makeConfig());
    expect(result).toContain("## Refactor API");
    expect(result).toContain("### Changes");
    expect(result).toContain("### Testing");
    expect(result).toContain("### Breaking Changes");
  });

  it("parseCommand returns null for just /mizumi (no subcommand)", () => {
    expect(parseCommand("/mizumi")).toBeNull();
  });

  it("parseCommand returns null for non-mizumi slash command", () => {
    expect(parseCommand("/approve")).toBeNull();
  });

  it("parseCommand handles /mizumi with extra spaces before args", () => {
    const result = parseCommand("/mizumi review  check security");
    expect(result).not.toBeNull();
    expect(result!.command).toBe("review");
    // The regex captures everything after the first space following the command
    expect(result!.args).toContain("check security");
  });

  it("parseCommand is case-sensitive (no match for /Mizumi)", () => {
    expect(parseCommand("/Mizumi describe")).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// parseCommand — additional edge cases
// ---------------------------------------------------------------------------

describe("parseCommand — edge cases", () => {
  it("returns null for whitespace-only input", () => {
    expect(parseCommand("   ")).toBeNull();
  });

  it("parses /mizumi with tab between command and args", () => {
    const result = parseCommand("/mizumi\treview\tfocus");
    // The regex uses \s+ which matches tabs
    expect(result).not.toBeNull();
    expect(result!.command).toBe("review");
  });

  it("parses /mizumi with single character subcommand", () => {
    const result = parseCommand("/mizumi x");
    expect(result).not.toBeNull();
    expect(result!.command).toBe("x");
  });

  it("parses /mizumi with numeric subcommand-like arg", () => {
    const result = parseCommand("/mizumi review 12345");
    expect(result?.args).toBe("12345");
  });

  it("returns null for /mizumi with only trailing slash", () => {
    // "/mizumi/" doesn't match /^\/mizumi\s+(\w+) because no space before subcommand
    expect(parseCommand("/mizumi/")).toBeNull();
  });

  it("returns null for just slash", () => {
    expect(parseCommand("/")).toBeNull();
  });

  it("parses /mizumi with special characters in args", () => {
    const result = parseCommand("/mizumi review check @mention #123");
    expect(result?.args).toContain("@mention");
    expect(result?.args).toContain("#123");
  });

  it("matches only ASCII word chars for subcommand (unicode in input)", () => {
    // \w matches [a-zA-Z0-9_], so "résumé" starts with "r" which is \w
    // but "é" is not \w, so the regex \w+ matches just "r"
    // There's a space before "résumé", so it becomes the subcommand
    const result = parseCommand("/mizumi résumé");
    expect(result).not.toBeNull();
    expect(result!.command).toBe("r");
    // "ésumé" is not captured as args because there's no whitespace between "r" and "é"
    expect(result!.args).toBe("");
  });

  it("args default to empty string when only command is present", () => {
    const result = parseCommand("/mizumi review");
    expect(result?.command).toBe("review");
    expect(result?.args).toBe("");
  });

  it("handles very long args string", () => {
    const longArgs = "a".repeat(1000);
    const result = parseCommand(`/mizumi review ${longArgs}`);
    expect(result?.args).toBe(longArgs);
  });
});

// ---------------------------------------------------------------------------
// generateDescription — additional edge cases
// ---------------------------------------------------------------------------

describe("generateDescription — edge cases", () => {
  beforeEach(() => {
    mockGenerateObject.mockReset();
  });

  function makeConfig() {
    return {
      provider: "openai" as const, model: "gpt-4.1-mini", baseUrl: "",
      profile: "chill" as const, maxComments: 15, language: "en-US",
      selfCritique: true, confidenceThreshold: 80, autoReview: true,
      autoPauseAfter: 5, excludePatterns: [], tierRouting: true,
      smallDiffThreshold: 50, securityPaths: [],
    };
  }

  it("handles changes list with single item", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Small fix", summary: "Minimal change", changes: ["Fix typo"],
        testing: "Visual", breaking: "None",
      },
      usage: { inputTokens: 50, outputTokens: 20 },
    } as any);

    const result = await generateDescription("diff", "Fix", "typo", makeConfig());
    expect(result).toContain("- Fix typo");
    expect(result).not.toContain("\n- \n"); // No empty bullet
  });

  it("handles empty changes list gracefully", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "No changes", summary: "Empty diff", changes: [],
        testing: "None", breaking: "None",
      },
      usage: { inputTokens: 10, outputTokens: 5 },
    } as any);

    const result = await generateDescription("diff", "Empty", "nothing", makeConfig());
    expect(result).toContain("## No changes");
  });

  it("truncates diff at 50000 characters", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "T", summary: "T", changes: ["T"], testing: "T", breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const diff = "y".repeat(60000);
    await generateDescription(diff, "title", "body", makeConfig());

    const callOpts = mockGenerateObject.mock.calls[0][0] as any;
    // The raw diff portion is sliced to 50000 before being embedded in prompt
    const diffPart = callOpts.prompt.split("Diff:\n")[1];
    expect(diffPart.length).toBeLessThanOrEqual(51000); // includes surrounding prompt text after diff
  });

  it("handles PR title with special characters", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Fix XSS", summary: "Security fix", changes: ["Sanitize input"],
        testing: "Security scan", breaking: "None",
      },
      usage: { inputTokens: 100, outputTokens: 50 },
    } as any);

    const result = await generateDescription("diff", 'Fix <script>alert("xss")</script>', "body", makeConfig());
    expect(result).toContain("Fix XSS");
  });

  it("handles very long breaking changes text", async () => {
    const longBreaking = "B".repeat(5000);
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "API v2", summary: "Major breaking change", changes: ["Rewrite API"],
        testing: "Full suite", breaking: longBreaking,
      },
      usage: { inputTokens: 200, outputTokens: 100 },
    } as any);

    const result = await generateDescription("diff", "API", "body", makeConfig());
    expect(result).toContain("### Breaking Changes");
    expect(result).toContain(longBreaking);
  });

  it("generates markdown heading with ## prefix for title", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "Update dependencies", summary: "Bump deps", changes: ["Bump axios"],
        testing: "CI", breaking: "None",
      },
      usage: { inputTokens: 50, outputTokens: 25 },
    } as any);

    const result = await generateDescription("diff", "Deps", "body", makeConfig());
    expect(result).toMatch(/^## Update dependencies/m);
  });

  it("includes proper sections in output order", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "T", summary: "S", changes: ["C1"], testing: "Test", breaking: "Breaking!",
      },
      usage: { inputTokens: 50, outputTokens: 25 },
    } as any);

    const result = await generateDescription("diff", "T", "B", makeConfig());
    const titleIdx = result.indexOf("## T");
    const changesIdx = result.indexOf("### Changes");
    const testingIdx = result.indexOf("### Testing");
    const breakingIdx = result.indexOf("### Breaking Changes");
    const attributionIdx = result.indexOf("Generated by Mizumi");

    expect(titleIdx).toBeLessThan(changesIdx);
    expect(changesIdx).toBeLessThan(testingIdx);
    expect(testingIdx).toBeLessThan(breakingIdx);
    expect(breakingIdx).toBeLessThan(attributionIdx);
  });

  it("handles diffFiles with exactly 2 files (triggers diagram check)", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "T", summary: "S", changes: ["C"], testing: "T", breaking: "None",
      },
      usage: { inputTokens: 50, outputTokens: 25 },
    } as any);

    const diffFiles = [
      { path: "src/a.ts", additions: 10, deletions: 5 },
      { path: "src/b.ts", additions: 15, deletions: 3 },
    ];
    const result = await generateDescription("diff", "T", "B", makeConfig(), diffFiles);
    // generateArchDiagram is mocked to return null so no diagram in output
    expect(result).not.toContain("Change Architecture");
  });

  it("handles diffFiles with empty array (no diagram)", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "T", summary: "S", changes: ["C"], testing: "T", breaking: "None",
      },
      usage: { inputTokens: 50, outputTokens: 25 },
    } as any);

    const result = await generateDescription("diff", "T", "B", makeConfig(), []);
    expect(result).not.toContain("Change Architecture");
  });

  it("uses sanitized inputs in prompt", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "T", summary: "S", changes: ["C"], testing: "T", breaking: "None",
      },
      usage: { inputTokens: 50, outputTokens: 25 },
    } as any);

    await generateDescription("diff content", "My Title", "My Body", makeConfig());
    const callOpts = mockGenerateObject.mock.calls[0][0] as any;
    expect(callOpts.prompt).toContain("My Title");
    expect(callOpts.prompt).toContain("My Body");
  });

  it("passes model from createModel to generateObject", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "T", summary: "S", changes: ["C"], testing: "T", breaking: "None",
      },
      usage: { inputTokens: 50, outputTokens: 25 },
    } as any);

    await generateDescription("diff", "T", "B", makeConfig());
    const callOpts = mockGenerateObject.mock.calls[0][0] as any;
    expect(callOpts.model).toBe("mock-model");
  });

  it("passes schema to generateObject", async () => {
    mockGenerateObject.mockResolvedValue({
      object: {
        title: "T", summary: "S", changes: ["C"], testing: "T", breaking: "None",
      },
      usage: { inputTokens: 50, outputTokens: 25 },
    } as any);

    await generateDescription("diff", "T", "B", makeConfig());
    const callOpts = mockGenerateObject.mock.calls[0][0] as any;
    expect(callOpts.schema).toBeDefined();
  });
});
