import { describe, it, expect } from "vitest";
import { detectSlop } from "../slop.js";

describe("detectSlop", () => {
  it("returns 0 score for empty diff", () => {
    const result = detectSlop("", 0, 0, 0, []);
    expect(result.score).toBe(0);
    expect(result.isSlop).toBe(false);
    expect(result.reasons).toHaveLength(0);
  });

  it("is not slop for a normal small PR", () => {
    const diff = [
      "+import { foo } from './bar';",
      "+",
      "+export function baz() {",
      "+  return foo();",
      "+}",
    ].join("\n");
    const result = detectSlop(diff, 4, 1, 1, ["src/app.ts"]);
    expect(result.score).toBeLessThan(60);
    expect(result.isSlop).toBe(false);
  });

  it("detects high addition ratio", () => {
    const diff = Array.from({ length: 600 }, (_, i) => `+line ${i}`).join("\n");
    const result = detectSlop(diff, 600, 0, 1, ["src/gen.ts"]);
    expect(result.score).toBeGreaterThanOrEqual(30);
    expect(result.reasons).toContain("high addition ratio");
  });

  it("detects low semantic density with long lines", () => {
    const longLine = "+".padEnd(200, "x");
    const diff = Array.from({ length: 30 }, () => longLine).join("\n");
    const result = detectSlop(diff, 30, 5, 2, ["src/a.ts", "src/b.ts"]);
    expect(result.score).toBeGreaterThanOrEqual(25);
    expect(result.reasons).toContain("low semantic density");
  });

  it("detects repetitive code", () => {
    const dupLine = "+export function handleThing() { return null; }";
    const diff = Array.from({ length: 25 }, () => dupLine).join("\n");
    const result = detectSlop(diff, 25, 0, 1, ["src/handlers.ts"]);
    expect(result.score).toBeGreaterThanOrEqual(30);
    expect(result.reasons).toContain("repetitive code");
  });

  it("detects boilerplate markers", () => {
    const diff = [
      "+// Copyright 2024 Acme Corp",
      "+// Auto-generated by tool",
      "+export const x = 1;",
    ].join("\n");
    const result = detectSlop(diff, 3, 0, 1, ["src/gen.ts"]);
    expect(result.score).toBeGreaterThanOrEqual(40);
    expect(result.reasons).toContain("boilerplate markers");
  });

  it("score stays below threshold for a legitimate large PR", () => {
    const lines = Array.from({ length: 200 }, (_, i) =>
      `+const val${i} = compute(${i});`.padEnd(60, " ")
    );
    const diff = lines.join("\n");
    const result = detectSlop(diff, 200, 50, 5, [
      "src/a.ts", "src/b.ts", "src/c.ts", "src/d.ts", "src/e.ts",
    ]);
    expect(result.score).toBeLessThan(60);
    expect(result.isSlop).toBe(false);
  });

  it("caps boilerplate score at 40", () => {
    const diff = [
      "+// Copyright 2024",
      "+// Auto-generated by tool",
      "+// Generated by AI",
      "+@Generated",
      "+DO NOT EDIT",
      "+export const x = 1;",
    ].join("\n");
    const result = detectSlop(diff, 6, 0, 1, ["src/gen.ts"]);
    // boilerplate contributes at most 40
    const boilerplateScore = Math.min(5 * 20, 40);
    expect(result.score).toBeGreaterThanOrEqual(boilerplateScore);
  });
});
