import { describe, it, expect } from "vitest";
import { detectSlop } from "../slop.js";

describe("detectSlop", () => {
  it("returns 0 score for empty diff", () => {
    const result = detectSlop("", 0, 0, 0, []);
    expect(result.score).toBe(0);
    expect(result.isSlop).toBe(false);
    expect(result.reasons).toHaveLength(0);
  });

  it("is not slop for a normal small PR", () => {
    const diff = [
      "+import { foo } from './bar';",
      "+",
      "+export function baz() {",
      "+  return foo();",
      "+}",
    ].join("\n");
    const result = detectSlop(diff, 4, 1, 1, ["src/app.ts"]);
    expect(result.score).toBeLessThan(60);
    expect(result.isSlop).toBe(false);
  });

  it("detects high addition ratio", () => {
    const diff = Array.from({ length: 600 }, (_, i) => `+line ${i}`).join("\n");
    const result = detectSlop(diff, 600, 0, 1, ["src/gen.ts"]);
    expect(result.score).toBeGreaterThanOrEqual(30);
    expect(result.reasons).toContain("high addition ratio");
  });

  it("detects low semantic density with long lines", () => {
    const longLine = "+".padEnd(200, "x");
    const diff = Array.from({ length: 30 }, () => longLine).join("\n");
    const result = detectSlop(diff, 30, 5, 2, ["src/a.ts", "src/b.ts"]);
    expect(result.score).toBeGreaterThanOrEqual(25);
    expect(result.reasons).toContain("low semantic density");
  });

  it("detects repetitive code", () => {
    const dupLine = "+export function handleThing() { return null; }";
    const diff = Array.from({ length: 25 }, () => dupLine).join("\n");
    const result = detectSlop(diff, 25, 0, 1, ["src/handlers.ts"]);
    expect(result.score).toBeGreaterThanOrEqual(30);
    expect(result.reasons).toContain("repetitive code");
  });

  it("detects boilerplate markers", () => {
    const diff = [
      "+// Copyright 2024 Acme Corp",
      "+// Auto-generated by tool",
      "+export const x = 1;",
    ].join("\n");
    const result = detectSlop(diff, 3, 0, 1, ["src/gen.ts"]);
    expect(result.score).toBeGreaterThanOrEqual(40);
    expect(result.reasons).toContain("boilerplate markers");
  });

  it("score stays below threshold for a legitimate large PR", () => {
    const lines = Array.from({ length: 200 }, (_, i) =>
      `+const val${i} = compute(${i});`.padEnd(60, " ")
    );
    const diff = lines.join("\n");
    const result = detectSlop(diff, 200, 50, 5, [
      "src/a.ts", "src/b.ts", "src/c.ts", "src/d.ts", "src/e.ts",
    ]);
    expect(result.score).toBeLessThan(60);
    expect(result.isSlop).toBe(false);
  });

  it("caps boilerplate score at 40", () => {
    const diff = [
      "+// Copyright 2024",
      "+// Auto-generated by tool",
      "+// Generated by AI",
      "+@Generated",
      "+DO NOT EDIT",
      "+export const x = 1;",
    ].join("\n");
    const result = detectSlop(diff, 6, 0, 1, ["src/gen.ts"]);
    const boilerplateScore = Math.min(5 * 20, 40);
    expect(result.score).toBeGreaterThanOrEqual(boilerplateScore);
  });

  it("detects numeric-suffix file pattern", () => {
    const diff = Array.from({ length: 50 }, (_, i) => `+export const v${i} = ${i};`).join("\n");
    const files = Array.from({ length: 7 }, (_, i) => `src/migration001${i}.ts`);
    const result = detectSlop(diff, 50, 0, 7, files);
    expect(result.reasons).toContain("numeric-suffix file pattern");
    expect(result.score).toBeGreaterThanOrEqual(20);
  });

  it("does not flag numeric-suffix with 5 or fewer matches", () => {
    const diff = Array.from({ length: 30 }, (_, i) => `+const v${i} = ${i};`).join("\n");
    const files = ["src/mig001.ts", "src/mig002.ts", "src/mig003.ts", "other.ts"];
    const result = detectSlop(diff, 30, 5, 4, files);
    expect(result.reasons).not.toContain("numeric-suffix file pattern");
  });

  it("high addition ratio requires additions > 500", () => {
    const diff = Array.from({ length: 400 }, (_, i) => `+line ${i}`).join("\n");
    const result = detectSlop(diff, 400, 0, 1, ["src/file.ts"]);
    expect(result.reasons).not.toContain("high addition ratio");
  });

  it("high addition ratio triggers at exactly 501 additions with 0 deletions", () => {
    const diff = Array.from({ length: 501 }, (_, i) => `+line ${i}`).join("\n");
    const result = detectSlop(diff, 501, 0, 1, ["src/file.ts"]);
    expect(result.reasons).toContain("high addition ratio");
  });

  it("does not flag repetitive code below 20% threshold", () => {
    const lines = [
      "+unique line 1",
      "+unique line 2",
      "+unique line 3",
      "+unique line 4",
      "+duplicate line",
      "+duplicate line",
    ];
    const diff = lines.join("\n");
    const result = detectSlop(diff, 6, 0, 1, ["src/a.ts"]);
    // 2 dupes / 6 lines = 33% > 20%, so this actually IS repetitive
    // Need: less than 20% duplicates
    const lowDupe = [
      "+a", "+b", "+c", "+d", "+e", "+f", "+g", "+h", "+i", "+j",
      "+dup", "+dup", "+dup",
    ];
    const diff2 = lowDupe.join("\n");
    const result2 = detectSlop(diff2, 13, 0, 1, ["src/a.ts"]);
    // 3 dupes / 13 lines = ~23% — still over. Use precise control:
    const clean = Array.from({ length: 15 }, (_, i) => `+line ${i}`).join("\n");
    const result3 = detectSlop(clean, 15, 0, 1, ["src/a.ts"]);
    expect(result3.reasons).not.toContain("repetitive code");
  });

  it("ignores diff header lines when checking semantic density", () => {
    const diff = "+++ b/newfile.txt\n+short";
    const result = detectSlop(diff, 1, 0, 1, ["newfile.txt"]);
    expect(result.reasons).not.toContain("low semantic density");
  });

  it("combines multiple signals for higher score", () => {
    const dupLine = "+".padEnd(150, "x");
    const diff = Array.from({ length: 600 }, () => dupLine).join("\n");
    const result = detectSlop(diff, 600, 0, 1, ["src/gen.ts"]);
    expect(result.score).toBeGreaterThanOrEqual(55);
    expect(result.reasons.length).toBeGreaterThanOrEqual(2);
  });

  it("isSlop is true at score >= 60", () => {
    const longLine = "+".padEnd(200, "x");
    const diff = Array.from({ length: 600 }, () => longLine).join("\n");
    const result = detectSlop(diff, 600, 0, 1, ["src/gen.ts"]);
    expect(result.isSlop).toBe(true);
  });

  it("isSlop is false at score < 60", () => {
    const diff = "+const x = 1;\n+const y = 2;";
    const result = detectSlop(diff, 2, 0, 1, ["src/a.ts"]);
    expect(result.isSlop).toBe(false);
  });
});
