/**
 * PR description generator — analyzes diff and produces a structured description.
 * Triggered via `/mizumi describe` command.
 */
import { generateText, Output } from "ai";
import { createAnthropic } from "@ai-sdk/anthropic";
import { createOpenAI } from "@ai-sdk/openai";
import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { z } from "zod";
import { MizumiConfig, requireApiKey } from "./config.js";

const DescriptionSchema = z.object({
  title: z.string().describe("Concise PR title in imperative mood"),
  summary: z.string().describe("1-2 sentence summary of what this PR does and why"),
  changes: z.array(z.string()).describe("Bullet list of key changes"),
  testing: z.string().describe("How to verify these changes work"),
  breaking: z.string().optional().describe("Breaking changes if any, or 'None'"),
});

function createModel(config: MizumiConfig) {
  const apiKey = requireApiKey(config.provider);
  switch (config.provider) {
    case "anthropic": return createAnthropic({ apiKey })(config.model);
    case "openai": return createOpenAI({ apiKey })(config.model);
    case "google": return createGoogleGenerativeAI({ apiKey })(config.model);
    case "openrouter": return createOpenAI({ baseURL: "https://openrouter.ai/api/v1", apiKey, name: "openrouter" }).chat(config.model);
    case "local": return createOpenAI({ baseURL: config.baseUrl || "http://localhost:11434/v1", apiKey, name: "local" }).chat(config.model);
    case "custom": return createOpenAI({ baseURL: config.baseUrl || process.env.CUSTOM_BASE_URL || "", apiKey, name: "custom" }).chat(config.model);
  case "nvidia": return createOpenAI({ baseURL: "https://integrate.api.nvidia.com/v1", apiKey, name: "nvidia" }).chat(config.model);
  }
}

export async function generateDescription(
  diffText: string,
  prTitle: string,
  prBody: string,
  config: MizumiConfig
): Promise<string> {
  const model = createModel(config);
  const { output } = await generateText({
    model,
    system: "You generate clear, structured PR descriptions from diff content. Use imperative mood. Be concise.",
    prompt: `Generate a PR description for this diff.

Current title: ${prTitle || "(none)"}
Current body: ${prBody || "(none)"}

Diff:
${diffText.slice(0, 50000)}

Respond with structured JSON matching the schema.`,
    output: Output.object({ schema: DescriptionSchema }),
    maxOutputTokens: 2048,
  });

  const desc = output as z.infer<typeof DescriptionSchema>;
  let body = `## ${desc.title}\n\n${desc.summary}\n\n### Changes\n`;
  for (const c of desc.changes) {
    body += `- ${c}\n`;
  }
  body += `\n### Testing\n${desc.testing}\n`;
  if (desc.breaking && desc.breaking !== "None") {
    body += `\n### Breaking Changes\n${desc.breaking}\n`;
  }
  body += "\n---\n*Generated by Mizumi. Verify before using.*";
  return body;
}

export function parseCommand(body: string): { command: string; args: string } | null {
  const match = body.match(/^\/mizumi\s+(\w+)(?:\s+(.+))?/);
  if (!match) return null;
  return { command: match[1], args: match[2] || "" };
}
