/**
 * PR description generator — analyzes diff and produces a structured description.
 * Triggered via `/mizumi describe` command.
 */
import { generateObject } from "ai";
import { z } from "zod";
import { MizumiConfig } from "./config.js";
import { createModel } from "./models.js";
import { generateArchDiagram } from "./diagram.js";
import { sanitizeInput } from "./sanitize.js";

const DescriptionSchema = z.object({
  title: z.string().describe("Concise PR title in imperative mood"),
  summary: z.string().describe("1-2 sentence summary of what this PR does and why"),
  changes: z.array(z.string()).describe("Bullet list of key changes"),
  testing: z.string().describe("How to verify these changes work"),
  breaking: z.string().optional().describe("Breaking changes if any, or 'None'"),
});

export async function generateDescription(
  diffText: string,
  prTitle: string,
  prBody: string,
  config: MizumiConfig,
  diffFiles?: Array<{ path: string; additions: number; deletions: number }>
): Promise<string> {
  const model = createModel(config);
  const safeTitle = sanitizeInput(prTitle || "(none)");
  const safeBody = sanitizeInput(prBody || "(none)");
  const safeDiff = sanitizeInput(diffText.slice(0, 50000));

  const { object: output } = await generateObject({
    model,
    system: "You generate clear, structured PR descriptions from diff content. Use imperative mood. Be concise.",
    prompt: `Generate a PR description for this diff.

Current title: ${safeTitle}
Current body: ${safeBody}

Diff:
${safeDiff}

Respond with structured JSON matching the schema.`,
    schema: DescriptionSchema,
    maxOutputTokens: 2048,
  });

  const desc = output as z.infer<typeof DescriptionSchema>;
  let body = `## ${desc.title}\n\n${desc.summary}\n\n### Changes\n`;
  for (const c of desc.changes) {
    body += `- ${c}\n`;
  }
  body += `\n### Testing\n${desc.testing}\n`;
  if (desc.breaking && desc.breaking !== "None") {
    body += `\n### Breaking Changes\n${desc.breaking}\n`;
  }

  if (diffFiles && diffFiles.length >= 2) {
    const diagram = generateArchDiagram(diffFiles);
    if (diagram) {
      body += `\n### Change Architecture\n\n${diagram}\n`;
    }
  }

  body += "\n---\n*Generated by Mizumi. Verify before using.*";
  return body;
}

export function parseCommand(body: string): { command: string; args: string } | null {
  const match = body.match(/^\/mizumi\s+(\w+)(?:\s+(.+))?/);
  if (!match) return null;
  return { command: match[1], args: match[2] || "" };
}
