/**
 * Slop detection — heuristic check for low-quality AI-generated PRs.
 * Pattern: high addition count, low semantic density, repetitive structures.
 */

export interface SlopResult {
  isSlop: boolean;
  score: number;       // 0-100, higher = more likely AI garbage
  reasons: string[];
}

const BOILERPLATE_RES = [
  /\/\/ Copyright\b/i,
  /\/\/ Auto-generated\b/i,
  /\/\/ Generated by\b/i,
  /@Generated\b/,
  /DO NOT EDIT\b/,
];

const NUMERIC_SUFFIX_RE = /^(.+?)(\d+)\.\w+$/;

export function detectSlop(
  diffText: string,
  totalAdditions: number,
  totalDeletions: number,
  _fileCount: number,
  changedFiles: string[],
): SlopResult {
  let score = 0;
  const reasons: string[] = [];

  if (diffText.length === 0) return { isSlop: false, score: 0, reasons };

  // High addition ratio: additions > 500 and additions/deletions > 10
  if (totalAdditions > 500 && (totalDeletions === 0 || totalAdditions / totalDeletions > 10)) {
    score += 30;
    reasons.push("high addition ratio");
  }

  // Low semantic density: average added-line length > 120 chars
  const addedLines = diffText.split("\n").filter((l) => l.startsWith("+") && !l.startsWith("+++"));
  if (addedLines.length > 0) {
    const avgLen = addedLines.reduce((s, l) => s + l.length, 0) / addedLines.length;
    if (avgLen > 120) { score += 25; reasons.push("low semantic density"); }
  }

  // Repetitive structures: >20% duplicate lines in additions
  if (addedLines.length > 0) {
    const seen = new Map<string, number>();
    for (const line of addedLines) { seen.set(line, (seen.get(line) ?? 0) + 1); }
    const dupes = [...seen.values()].filter((c) => c > 1).reduce((s, c) => s + c, 0);
    if (dupes / addedLines.length > 0.2) { score += 30; reasons.push("repetitive code"); }
  }

  // Boilerplate patterns: +20 per unique match, max +40
  const matched = new Set<string>();
  for (const re of BOILERPLATE_RES) { if (re.test(diffText)) matched.add(re.source); }
  if (matched.size > 0) {
    score += Math.min(matched.size * 20, 40);
    reasons.push("boilerplate markers");
  }

  // Many similar filenames: >5 files with same prefix + numeric suffix
  const prefixCounts = new Map<string, number>();
  for (const f of changedFiles) {
    const m = f.match(NUMERIC_SUFFIX_RE);
    if (m) prefixCounts.set(m[1], (prefixCounts.get(m[1]) ?? 0) + 1);
  }
  if ([...prefixCounts.values()].some((c) => c > 5)) {
    score += 20;
    reasons.push("numeric-suffix file pattern");
  }

  return { isSlop: score >= 60, score, reasons };
}
