/**
 * /mizumi test — generate test skeletons for critical/high findings.
 * Uses LLM to produce test code from review findings + diff context.
 */
import { generateText, Output } from "ai";
import { createAnthropic } from "@ai-sdk/anthropic";
import { createOpenAI } from "@ai-sdk/openai";
import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { z } from "zod";
import { MizumiConfig, getApiKey } from "./config.js";

const TestSchema = z.object({
  tests: z.array(z.object({
    file: z.string().describe("Test file path, e.g. src/__tests__/foo.test.ts"),
    code: z.string().describe("Complete test code block"),
  })).describe("Generated test files"),
});

function createModel(config: MizumiConfig) {
  const apiKey = getApiKey(config.provider);
  switch (config.provider) {
    case "anthropic": return createAnthropic({ apiKey })(config.model);
    case "openai": return createOpenAI({ apiKey })(config.model);
    case "google": return createGoogleGenerativeAI({ apiKey })(config.model);
    case "openrouter": return createOpenAI({ baseURL: "https://openrouter.ai/api/v1", apiKey, name: "openrouter" }).chat(config.model);
    case "local": return createOpenAI({ baseURL: config.baseUrl || "http://localhost:11434/v1", apiKey: apiKey || "dummy", name: "local" }).chat(config.model);
    case "nvidia": return createOpenAI({ baseURL: "https://integrate.api.nvidia.com/v1", apiKey, name: "nvidia" }).chat(config.model);
  }
}

export async function generateTests(
  diffText: string,
  findings: Array<{ file: string; line: number; severity: string; category: string; message: string; suggestion?: string }>,
  config: MizumiConfig
): Promise<string> {
  if (findings.length === 0) return "No critical/high findings to generate tests for.";

  const criticalFindings = findings
    .filter((f) => f.severity === "critical" || f.severity === "high")
    .slice(0, 5);

  if (criticalFindings.length === 0) return "No critical/high findings to generate tests for.";

  const model = createModel(config);
  const findingsSummary = criticalFindings
    .map((f) => `- [${f.severity}] ${f.file}:${f.line} (${f.category}): ${f.message}${f.suggestion ? ` — Suggestion: ${f.suggestion}` : ""}`)
    .join("\n");

  const { output } = await generateText({
    model,
    system: "You generate vitest test code that would catch the specific bugs/security issues described in review findings. Write focused, minimal tests — one test per finding. Use vitest describe/it/expect syntax.",
    prompt: `Generate vitest tests for these review findings:

${findingsSummary}

Changed code diff (for context):
${diffText.slice(0, 30000)}

Respond with structured JSON matching the schema.`,
    output: Output.object({ schema: TestSchema }),
    maxOutputTokens: 2048,
  });

  const result = output as z.infer<typeof TestSchema>;
  if (result.tests.length === 0) return "LLM did not generate any test files.";

  let body = "## Generated Tests\n\n";
  for (const t of result.tests) {
    body += `### ${t.file}\n\`\`\`typescript\n${t.code}\n\`\`\`\n\n`;
  }
  body += "---\n*Generated by Mizumi. Review before committing.*";
  return body;
}
