/**
 * /mizumi test — generate test skeletons for critical/high findings.
 * Uses LLM to produce test code from review findings + diff context.
 */
import { generateObject } from "ai";
import { z } from "zod";
import { MizumiConfig } from "./config.js";
import { createModel } from "./models.js";

const TestSchema = z.object({
  tests: z.array(z.object({
    file: z.string().describe("Test file path, e.g. src/__tests__/foo.test.ts"),
    code: z.string().describe("Complete test code block"),
  })).describe("Generated test files"),
});

export async function generateTests(
  diffText: string,
  findings: Array<{ file: string; line: number; severity: string; category: string; message: string; suggestion?: string }>,
  config: MizumiConfig
): Promise<string> {
  if (findings.length === 0) return "No critical/high findings to generate tests for.";

  const criticalFindings = findings
    .filter((f) => f.severity === "critical" || f.severity === "high")
    .slice(0, 5);

  if (criticalFindings.length === 0) return "No critical/high findings to generate tests for.";

  const model = createModel(config);
  const findingsSummary = criticalFindings
    .map((f) => `- [${f.severity}] ${f.file}:${f.line} (${f.category}): ${f.message}${f.suggestion ? ` — Suggestion: ${f.suggestion}` : ""}`)
    .join("\n");

  const { object: output } = await generateObject({
    model,
    system: "You generate vitest test code that would catch the specific bugs/security issues described in review findings. Write focused, minimal tests — one test per finding. Use vitest describe/it/expect syntax.",
    prompt: `Generate vitest tests for these review findings:

${findingsSummary}

Changed code diff (for context):
${diffText.slice(0, 30000)}

Respond with structured JSON matching the schema.`,
    schema: TestSchema,
    maxOutputTokens: 2048,
  });

  const result = output as z.infer<typeof TestSchema>;
  if (result.tests.length === 0) return "LLM did not generate any test files.";

  let body = "## Generated Tests\n\n";
  for (const t of result.tests) {
    body += `### ${t.file}\n\`\`\`typescript\n${t.code}\n\`\`\`\n\n`;
  }
  body += "---\n*Generated by Mizumi. Review before committing.*";
  return body;
}
